export const FINANCIAL_CATEGORIES_SCHEMA: Record<string, string[]> = {
  "Income": [
    "Dividends",
    "Interest Earned",
    "Tax Refund",
    "Wages",
    "Other Income",
  ],
  "Transfer In": [
    "Cash Advances And Loans",
    "Deposit",
    "Investment And Retirement Funds",
    "Savings",
    "Account Transfer",
    "Other Transfer In",
  ],
  "Transfer Out": [
    "Investment And Retirement Funds",
    "Savings",
    "Withdrawal",
    "Account Transfer",
    "Other Transfer Out",
  ],
  "Loan Payments": [
    "Car Payment",
    "Credit Card Payment",
    "Personal Loan Payment",
    "Mortgage Payment",
    "Student Loan Payment",
    "Other Payment",
  ],
  "Bank Fees": [
    "Atm Fees",
    "Foreign Transaction Fees",
    "Insufficient Funds",
    "Interest Charge",
    "Overdraft Fees",
    "Other Bank Fees",
  ],
  "Entertainment": [
    "Casinos And Gambling",
    "Sporting Events Amusement Parks And Museums",
    "Life While Travelling",
    "Hockey",
    "General Entertainment",
  ],
  "Food And Drink": [
    "Beer Wine And Liquor",
    "Coffee",
    "Groceries",
    "Snackies and Drinks",
    "Restaurant",
  ],
  "General Merchandise": [
    "Books",
    "Clothing And Accessories",
    "Convenience Stores",
    "Electronics",
    "Gifts",
    "Office Supplies",
    "Pet Supplies",
    "Sporting Goods",
    "Kitchen Supplies",
    "Other General Merchandise",
  ],
  "Home Improvement": [
    "Furniture",
    "Hardware",
    "Repair And Maintenance",
    "Security",
    "Other Home Improvement",
  ],
  "Medical": [
    "Dental Care",
    "Eye Care",
    "Nursing Care",
    "Pharmacies And Supplements",
    "Primary Care",
    "Veterinary Services",
    "Other Medical",
  ],
  "Personal Care": [
    "Gyms And Fitness Centers",
    "Hair And Beauty",
    "Laundry And Dry Cleaning",
    "Other Personal Care",
  ],
  "General Services": [
    "Subscriptions",
    "Education",
    "Insurance",
    "Postage And Shipping",
    "Storage",
    "Other General Services",
  ],
  "Government And Non Profit": [
    "Donations",
    "Government Departments And Agencies",
    "Tax Payment",
    "Other Government And Non Profit",
  ],
  "Transportation": [
    "Bikes And Scooters",
    "Gas",
    "Parking",
    "Public Transit",
    "Taxis And Ride Shares",
    "Tolls",
    "Other Transportation",
  ],
  "Travel": ["Flights", "Lodging", "Rental Cars", "Trains"],
  "Rent And Utilities": [
    "Gas And Electricity",
    "Internet And Cable",
    "Rent",
    "Sewage And Waste Management",
    "Telephone",
    "Water",
    "Other Utilities",
  ],
};

export const CATEGORY_KEYS = Object.keys(FINANCIAL_CATEGORIES_SCHEMA);
